# Generated by Django 4.1.4 on 2022-12-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="link",
            new_name="links",
        ),
    ]
